# Generated by Django 4.2.27 on 2025-12-13 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeafScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Healthy', 'Healthy'), ('Disease', 'Affected by Disease'), ('Deficiency', 'Nutrient Deficiency')], max_length=20)),
                ('deficiency_type', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scanner_app.leafscan')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
                ('treatment', models.TextField()),
                ('tips', models.TextField()),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scanner_app.scanresult')),
            ],
        ),
    ]
