# Generated by Django 4.2.27 on 2025-12-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='status',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='recommendation',
            field=models.TextField(default='No recommendation available'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_recommendation', to='scanner_app.scanresult'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='confidence_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='deficiency_type',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner_app.leafscan'),
        ),
    ]
