# Generated by Django 6.0.1 on 2026-01-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_app', '0002_remove_scanresult_scan_remove_recommendation_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
