# Generated by Django 6.0.1 on 2026-01-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_app', '0003_scanresult_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='farm_type',
            field=models.CharField(default='Home Garden', max_length=255),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='heatmap',
            field=models.ImageField(blank=True, null=True, upload_to='heatmaps/'),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/'),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='location',
            field=models.CharField(default='Sankarnagar', max_length=255),
        ),
    ]
